### ISSUE TITLE
wdio-perfecto-service installation issue

### ISSUE THREAD

**Issue by rakesh747** [PerfectoMobileSA/wdio-perfecto-service#14]
Hi, below is the list of dependencies that I'm using and I'm unable to install wdio-perfecto-service using npm install wdio-perfecto-service --save-dev

    "dependencies": {
    "webdriverio": "^7.16.13"
    },
    "devDependencies": {
    "@babel/core": "^7.16.12",
    "@babel/preset-env": "^7.16.11",
    "@babel/register": "^7.16.9",
    "@wdio/cli": "^7.16.13",
    "@wdio/local-runner": "^7.16.13",
    "@wdio/mocha-framework": "^7.16.13",
    "@wdio/spec-reporter": "^7.16.13",
    "chromedriver": "^97.0.2",
    "wdio-chromedriver-service": "^7.2.6"
    },

**Comment by rakesh747** [comment]
error: npm ERR! In file included from /Users/gadirajr/Library/Caches/node-gyp/16.9.0/include/node/v8.h:30:
npm ERR! /Users/gadirajr/Library/Caches/node-gyp/16.9.0/include/node/v8-internal.h:489:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR! !std::is_same<Data, std::remove_cv_t>::value>::Perform(data);
npm ERR! ~~~~~^~~~~~~~~~~
npm ERR! remove_cv
npm ERR! /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
npm ERR! template struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR! ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/integer/src/integer.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: make failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.onExit (/Users/gadirajr/.nvm/versions/node/v16.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/Users/gadirajr/.nvm/versions/node/v16.9.0/bin/node" "/Users/gadirajr/.nvm/versions/node/v16.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/gadirajr/automation/wdio_perfecto/node_modules/integer
npm ERR! gyp ERR! node -v v16.9.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

**Comment by ksitwala-perfecto** [comment]
@rakesh747 - We no longer maintain this project. The Quantum Java framework is the official one that we support and maintain. 

If you intend to test using webdriver IO then you can connect with Perfecto cloud with any other open-source framework you may have.
